<a href="https://colab.research.google.com/github/kuwarbimal/machine-learning/blob/main/bostonhousing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets


In [ ]:
X, Y=datasets.load_boston(return_X_y=True)
print(X.shape, Y.shape)


(506, 13) (506,)


In [ ]:
print(X)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [ ]:
means=np.mean(X, axis=0)
means.shape


(13,)

In [ ]:
standard=np.std(X, axis=0)

In [ ]:
print(standard)

[8.59304135e+00 2.32993957e+01 6.85357058e+00 2.53742935e-01
 1.15763115e-01 7.01922514e-01 2.81210326e+01 2.10362836e+00
 8.69865112e+00 1.68370495e+02 2.16280519e+00 9.12046075e+01
 7.13400164e+00]


In [ ]:
np.mean(X-means, axis=0)


array([-3.05245508e-15,  2.07616094e-14, -2.80039496e-14, -1.18975975e-16,
        2.64171645e-16, -8.14105042e-15, -3.55271368e-14,  1.72018745e-15,
        4.68312258e-15,  3.37016317e-13, -2.34858246e-14,  7.63229620e-13,
       -3.56500073e-15])

In [ ]:
np.std((X-means)/standard, axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
Z=(X-means)/standard

In [ ]:
ones = np.ones((Z.shape[0], 1))
ones.shape

(506, 1)

In [ ]:
ZU=np.concatenate((ones, Z), axis=1)
ZU.shape

(506, 14)

In [ ]:
def linear_regression(X, Y, num_iterations, alpha):
  m, n = X.shape

  theta=np.zeros((n,1))
  for i in range(num_iterations):
    y_hat=np.matmul(X, theta).reshape((m,))

    J=np.sum((y_hat-Y)**2)/(2*m)

    Diff=(y_hat-Y).reshape((m,1))

    Product=X*Diff
    Summ=np.sum(Product, axis=0).reshape((n, 1))

    gradient=Summ/m
    theta=theta-alpha*gradient
  return theta, J

theta, J= linear_regression(ZU, Y, 100, 0.2)
print(theta, J)

[[22.53280632]
 [-0.87338929]
 [ 0.9869205 ]
 [-0.09301125]
 [ 0.71480711]
 [-1.94287374]
 [ 2.73583864]
 [-0.02767223]
 [-3.05907427]
 [ 2.05442141]
 [-1.41648666]
 [-2.02530706]
 [ 0.84977952]
 [-3.71604354]] 10.977250294886039


In [ ]:
ZU*Y.reshape((Y.shape[0],1))

array([[ 24.        , -10.07476653,   6.83591666, ..., -35.01600913,
         10.58524638, -25.81349531],
       [ 21.6       ,  -9.01452811, -10.53480308, ...,  -6.5468336 ,
          9.52672174, -10.6366903 ],
       [ 34.7       , -14.48175324, -16.92396605, ..., -10.51736694,
         13.75601669, -41.94284074],
       ...,
       [ 23.9       ,  -9.88137326, -11.65656452, ...,  28.11753332,
         10.54114119, -23.49483782],
       [ 22.        ,  -8.97080965, -10.72989202, ...,  25.88224824,
          8.87094772, -19.03663585],
       [ 11.9       ,  -4.93850193,  -5.80389614, ...,  13.99994337,
          5.248518  ,  -7.96179416]])

In [ ]:
np.sum(ZU, axis=0).shape

(14,)